/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package babytomcat;

public class App {

    public static void main(String[] args) {
        HttpServer1 server = new HttpServer1();
        System.out.println(Constants.WEB_ROOT);
        server.await();
    }
}
