/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package babytomcat;

public class App {

    public static void main(String[] args) {
        HttpServer server = new HttpServer();
        System.out.println(HttpServer.WEB_ROOT);
        server.await();
    }
}
